const SERVICE_IDENTIFIERS = {
    CONFIGURATION: Symbol.for('CONFIGURATION'),
    COMMAND_REGISTRY: Symbol.for('COMMAND_REGISTRY'),
    DATA_ACCESS: Symbol.for('DATA_ACCESS')
};

export default SERVICE_IDENTIFIERS;
